[package]
name = "dlctix"
version = "0.1.0"
edition = "2021"
authors = ["conduition <conduition@proton.me>"]
description = "Ticketed Discreet Log Contracts"
readme = "README.md"
license = "Unlicense"
repository = "https://github.com/conduition/ticketed-dlc"
keywords = ["dlc", "smart", "contract", "ticket", "auction"]

[dependencies]
bitcoin = { version = "0.31.1" }
hex = "0.4.3"
musig2 = { version = "0.0.4" }
rand = "0.8.5"
secp = { version = "0.2.1" }
secp256k1 = { version = "0.28.2", features = ["global-context"] }
sha2 = "0.10.8"

[package.metadata.docs.rs]
all-features = true
